package model.am.common;

import java.util.Map;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 28 16:30:50 IST 2020
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    String uploadData(String ifaceId, String parentIfaceId, Map processedData);

    String parentInterfaceId(String parentInterfaceName);
}
