package model.am.client;

import java.util.Map;

import model.am.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 28 16:30:50 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public String uploadData(String ifaceId, String parentIfaceId,
                             Map processedData) {
        Object _ret =
            this.riInvokeExportedMethod(this,"uploadData",new String [] {"java.lang.String","java.lang.String","java.util.Map"},new Object[] {ifaceId, parentIfaceId, processedData});
        return (String)_ret;
    }

    public String parentInterfaceId(String parentInterfaceName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"parentInterfaceId",new String [] {"java.lang.String"},new Object[] {parentInterfaceName});
        return (String)_ret;
    }
}
